### ISSUE TITLE
CAD Assembly File

### ISSUE THREAD

**Issue by someonewhohatelongname** [srl-ethz/osprey#1]
Hi, 
First of all, thank you for sharing this incredible project. I’ve gone through the repository, and I really appreciate the effort and time you've put into developing this. I was wondering if you might be willing to share the CAD assembly file of the entire platform. 
Many thanks in advance.

**Comment by erikbr01** [comment]
@mbloechli could you add an assembly to the repo?

**Comment by someonewhohatelongname** [comment]
> @mbloechli could you add an assembly to the repo?

Hi @erikbr01, 

Thank you so much for the response! I’ve actually managed to locate the assembly file in the repository cad_parts/098082_02.prt. Apologies for the confusion, and I really appreciate your help.

**Comment by mbloechli** [comment]
Thanks for the mention. I'll create a readme inside the cad folder so the next person can find it quicker.
